name: Trigger Website Rebuild

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  trigger-rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger website deployment
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DOCS_SYNC_TOKEN }}
          repository: dj-stripe/dj-stripe.github.io
          event-type: docs-updated
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'